fieldLayouts:
  426a61e1-4e14-4fd9-9ebc-41d00a7f47cd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  1239f913-a7cc-409f-b258-61455bcf681f:
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog-categories/{slug}'
structure:
  maxLevels: 1
  uid: 176e8123-fc33-4e42-920b-c30aec53f17a
