contentColumnType: text
fieldGroup: 3d7ec1aa-0ca8-4594-8570-2323e30a0f4d
handle: summary
instructions: 'Enter a brief, one or two sentence post summary'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
