enableVersioning: true
handle: about
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1239f913-a7cc-409f-b258-61455bcf681f:
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
